### ISSUE TITLE
Last digit of card number got deleted automatically.

### ISSUE THREAD

**Issue by xhkz** [thiago-Malaca/vue-credit-card#1]
Hi,

Thanks for your work.

The input formatting seems automatically removing the last digit in card number with the white space. It also happens to expiry input.

```html
<input name="number" type="tel" v-model="cardDetails.number" v-card-focus>
<input name="expiry" type="tel" v-model="cardDetails.expiry" v-card-focus>
```

I recorded a gif for this issue, during the input I did not touch backspace key:
![vue-credit-card](https://cloud.githubusercontent.com/assets/568340/23007154/b85eaaac-f45a-11e6-9f02-887efe7164f7.gif)

**Comment by thiago-Malaca** [comment]
Hi @xhkz,

Thanks for reporting this bug. You described the problem well.
