### ISSUE TITLE
Wiki please!

### ISSUE THREAD

**Issue by rnjailamba** [thiago-Malaca/vue-credit-card#10]
npm install vue-credit-card --save 
import Card from "vue-credit-card";

Got this error 
Failed to compile with 1 errors                                                                 

This dependency was not found:

I need to see some working code please, thanks!

**Comment by rnjailamba** [comment]
@thiago-Malaca

**Comment by rnjailamba** [comment]
@danielswiatek

**Comment by rnjailamba** [comment]
@xhkz

**Comment by rnjailamba** [comment]
@Google-Mac

**Comment by rnjailamba** [comment]
@thom7kick

**Comment by rnjailamba** [comment]
@kenyk7

**Comment by parker-codes** [comment]
@rnjailamba I went into the package source code and changed the preset to env because the 2015 preset is deprecated.

**Comment by rnjailamba** [comment]
thanks @Google-Mac
